---
title: EARN Studios
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  projects:
    title: Projects
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    feature-image: 
    author: 
    layout: post
    permalink: "/news/:title/"
- scope:
    path: ''
    type: pages
  values:
    intro: 
    layout: page
url: https://www.earnstudios.com
description: We’re an innovation studio that builds brands customers love and participate in growing.
permalink: pretty
exclude:
- bower.json
- Gemfile.lock
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-paginate-v2
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  auto_ids: false
  input: GFM
  hard_wrap: false
highlighter: rouge
colophon: https://www.garethjohnsdesign.com
company: EARN Studios
email: hello@earnstudios.com
analytics:
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %Y"
future: true
social:
  twitter: https://twitter.com/earnstudios
  medium: https://medium.com/earnstudios
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
pagination:
  collection: posts
  enabled: true
  per_page: 6
  limit: 0
  permalink: "/:num/"
  title: ":title — :num of :max"
  sort_field: date
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    slugify:
      mode: raw
      cased: true
    layouts:
    - tags.html
    title: Posts tagged with :tag
    permalink: "/tag/:tag"
imgix:
  source: earn-studios.imgix.net